import axios from 'axios'

const BASE_URL = 'http://localhost:3000'


const INDEX_DATA = [
  {
    id: 1,
    title: 'Horus Top Optic se ocupa cu:',
    text: 'Consultatii optica medicala gratuite indiferent daca se achizitioneaza sau nu produsele companiei. Furnizarea de produse si servicii de calitate superioara si la preturi minime.',
    button: 'Citeste mai mult',
    url: './Ocupa'
  },
  {
    id: 2,
    title: 'Consultanță',
    text: 'HORUS TOP OPTIC se adreseaza persoanelor care sunt in cautarea unor servicii prompte si de calitate, totul pentru un pret corect. Oferim: Prescriptie ocheari de vedere, gama variata de ochelari.',
    button: 'Citeste mai mult',
    url: './Consultanta'
  },
  {
    id: 3,
    title: 'Despre noi',
    text: 'HORUS TOP OPTIC desfasoara programul de servicii de optica medicala si protectia vederii pentru angajatii companiilor. Ochelari de vedere, rame, lentile de contact, ochelari de soare.',
    button: 'Citeste mai mult',
    url: './DespreNoi'
  },

]

const PRODUSE = [
  {
    "id": "DSC_0001",
    "clasa": "rame",
    "url": "/ochelari/DSC_0001.jpg",
    "carousel": ["/ochelari/DSC_0001.jpg", "/ochelari/DSC_0002.jpg"],
    "brand": "EFOR",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "285",
    "material": "plastic-metal",
    "culoare": "lila",
    "cod": "GR2039C3",
    "tipRama": " rama completa",
    "latimeLentile": "54 mm",
    "punteNazala": "18 mm",
    "lungimeBrat": "142mm",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0003",
    "clasa": "rame",
    "url": "/ochelari/DSC_0003.jpg",
    "carousel": ["/ochelari/DSC_0003.jpg", "/ochelari/DSC_0004.jpg"],
    "brand": "CONSUL",
    "stilRama": "oval",
    "pentru": "dama",
    "pret": "240",
    "material": "metal",
    "culoare": "maro-auriu",
    "cod": "A6924C37",
    "tipRama": "rama completa",
    "latimeLentile": "50 mm",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0005",
    "clasa": "rame",
    "url": "/ochelari/DSC_0005.jpg",
    "carousel": ["/ochelari/DSC_0005.jpg", "/ochelari/DSC_0006.jpg"],
    "brand": "MARINA",
    "stilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "300",
    "material": "metal-plastic",
    "culoare": "mov-argintiu",
    "cod": "M3010",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0007",
    "clasa": "rame",
    "url": "/ochelari/DSC_0007.jpg",
    "carousel": ["/ochelari/DSC_0007.jpg", "/ochelari/DSC_0008.jpg"],
    "brand": "SONE TRUST",
    "stilRama": "rotunda",
    "pentru": "dama",
    "pret": "330",
    "material": "METAL",
    "culoare": "grena-auriu",
    "cod": "S010C2",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "19",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0009",
    "clasa": "rame",
    "url": "/ochelari/DSC_0009.jpg",
    "carousel": ["/ochelari/DSC_0009.jpg", "/ochelari/DSC_0010.jpg"],
    "brand": "CORRADO",
    "stilRama": "oval",
    "pentru": "unisex",
    "pret": "340",
    "material": "metal",
    "culoare": "negru-verde",
    "cod": "KL9011 C34",
    "tipRama": "RAMA COMPLETA",
    "latimeLentile": "51",
    "punteNazala": "19",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0011",
    "clasa": "rame",
    "url": "/ochelari/DSC_0011.jpg",
    "carousel": ["/ochelari/DSC_0011.jpg", "/ochelari/DSC_0012.jpg"],
    "brand": "Tony Morgan",
    "stilRama": "oval",
    "pentru": "Unisex",
    "pret": "210",
    "material": "plastic",
    "culoare": "Negru/argintiu",
    "cod": "2099C2",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "20",
    "lungimeBrat": "123",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0013",
    "clasa": "rame",
    "url": "/ochelari/DSC_0013.jpg",
    "carousel": ["/ochelari/DSC_0013.jpg", "/ochelari/DSC_0014.jpg"],
    "brand": "NICKOO",
    "stilRama": "oval",
    "pentru": "unisex",
    "pret": "240",
    "material": "plastic",
    "culoare": "GRI",
    "cod": "NICK001",
    "tipRama": "rama coompleta",
    "latimeLentile": "51",
    "punteNazala": "20",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0015",
    "clasa": "rame",
    "url": "/ochelari/DSC_0015.jpg",
    "carousel": ["/ochelari/DSC_0015.jpg", "/ochelari/DSC_0016.jpg"],
    "brand": "CORRADO",
    "stilRama": "rotund",
    "pentru": "unisex",
    "pret": "285",
    "material": "plastic",
    "culoare": "negru/rosu",
    "cod": "88053C5",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "20",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0017",
    "clasa": "rame",
    "url": "/ochelari/DSC_0017.jpg",
    "carousel": ["/ochelari/DSC_0017.jpg", "/ochelari/DSC_0018.jpg"],
    "brand": "JACOPO",
    "stilRama": "oval",
    "pentru": "unisex",
    "pret": "210",
    "material": "plastic/metal",
    "culoare": "negru/rosu",
    "cod": "61735C5",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0019",
    "clasa": "rame",
    "url": "/ochelari/DSC_0019.jpg",
    "carousel": ["/ochelari/DSC_0019.jpg", "/ochelari/DSC_0021.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "309",
    "material": "plastic",
    "culoare": "maro",
    "cod": "A01016C7",
    "tipRama": "Rama completa",
    "latimeLentile": "53",
    "punteNazala": "15",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0022",
    "clasa": "rame",
    "url": "/ochelari/DSC_0022.jpg",
    "carousel": ["/ochelari/DSC_0022.jpg", "/ochelari/DSC_0023.jpg"],
    "brand": "CADRU OPTIC",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "330",
    "material": "acetat",
    "culoare": "alb",
    "cod": "R7006C17",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "15",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0024",
    "clasa": "rame",
    "url": "/ochelari/DSC_0024.jpg",
    "carousel": ["/ochelari/DSC_0024.jpg", "/ochelari/DSC_0025.jpg"],
    "brand": "CONSUL",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "345",
    "material": "acetat",
    "culoare": "roz",
    "cod": "88162c5",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0026",
    "clasa": "rame",
    "url": "/ochelari/DSC_0026.jpg",
    "carousel": ["/ochelari/DSC_0026.jpg", "/ochelari/DSC_0027.jpg"],
    "brand": "OLEISS",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "0",
    "material": "acetat",
    "culoare": "negru",
    "cod": "OL821C1Y",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "14",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0028",
    "clasa": "rame",
    "url": "/ochelari/DSC_0028.jpg",
    "carousel": ["/ochelari/DSC_0028.jpg", "/ochelari/DSC_0029.jpg"],
    "brand": "OLEISS",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "0",
    "material": "acetat",
    "culoare": "mov",
    "cod": "OL821c3y",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "14",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0030",
    "clasa": "rame",
    "url": "/ochelari/DSC_0030.jpg",
    "carousel": ["/ochelari/DSC_0030.jpg", "/ochelari/DSC_0031.jpg"],
    "brand": "CONSUL",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "0",
    "material": "acetat",
    "culoare": "grena/verde",
    "cod": "A01004C2",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0032",
    "clasa": "rame",
    "url": "/ochelari/DSC_0032.jpg",
    "carousel": ["/ochelari/DSC_0032.jpg", "/ochelari/DSC_0033.jpg"],
    "brand": "REMY MARTIN",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "0",
    "material": "metal/plastic",
    "culoare": "crem/auriu",
    "cod": "M011C5",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0034",
    "clasa": "rame",
    "url": "/ochelari/DSC_0034.jpg",
    "carousel": ["/ochelari/DSC_0034.jpg", "/ochelari/DSC_0035.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "330",
    "material": "acetat",
    "culoare": "negru",
    "cod": "T821C1A",
    "tipRama": "rama completa",
    "latimeLentila": "51",
    "punteNazala": "17",
    "lungimeBrat": "142",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0036",
    "clasa": "rame",
    "url": "/ochelari/DSC_0036.jpg",
    "carousel": ["/ochelari/DSC_0036.jpg", "/ochelari/DSC_0037.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "345",
    "material": "metal",
    "culoare": "tuquoise/auriu",
    "cod": "PB9048 ",
    "tipRama": "rama completa",
    "latimeLentile": "55",
    "punteNazala": "18",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0038",
    "clasa": "rame",
    "url": "/ochelari/DSC_0038.jpg",
    "carousel": ["/ochelari/DSC_0038.jpg", "/ochelari/DSC_0039.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "300",
    "material": "acetat",
    "culoare": "negru",
    "cod": "AS1901C1",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0040",
    "clasa": "rame",
    "url": "/ochelari/DSC_0040.jpg",
    "carousel": ["/ochelari/DSC_0040.jpg", "/ochelari/DSC_0041.jpg"],
    "brand": "CONSUL",
    "stilRama": "vintage",
    "pentru": "dama",
    "pret": "240",
    "material": "acetat",
    "culoare": "lila",
    "cod": "MA45C2",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "22",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0042",
    "clasa": "rame",
    "url": "/ochelari/DSC_0042.jpg",
    "carousel": ["/ochelari/DSC_0042.jpg", "/ochelari/DSC_0043.jpg"],
    "brand": "CONSUL",
    "stilRama": "vintage",
    "pentru": "dama",
    "pret": "240",
    "material": "acetat",
    "culoare": "albastru/kaki",
    "cod": "MA46C6",
    "tipRama": "rama completa",
    "latimeLentile": "47",
    "punteNazala": "22",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0044",
    "clasa": "rame",
    "url": "/ochelari/DSC_0044.jpg",
    "carousel": ["/ochelari/DSC_0044.jpg", "/ochelari/DSC_0045.jpg"],
    "brand": "CONSUL",
    "stilRama": "vintage",
    "pentru": "dama",
    "pret": "240",
    "material": "acetat",
    "culoare": "crem",
    "cod": "MA46C4",
    "tipRama": "rama completa",
    "latimeLentile": "46",
    "punteNazala": "22",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0046",
    "clasa": "rame",
    "url": "/ochelari/DSC_0046.jpg",
    "carousel": ["/ochelari/DSC_0046.jpg", "/ochelari/DSC_0047.jpg"],
    "brand": "DiVERONA",
    "stilRama": "rectangulara",
    "pentru": "dama",
    "pret": "260",
    "material": "acetat",
    "culoare": "mov-sclipici",
    "cod": "DV3002C149",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "143",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0048",
    "clasa": "rame",
    "url": "/ochelari/DSC_0048.jpg",
    "carousel": ["/ochelari/DSC_0048.jpg", "/ochelari/DSC_0049.jpg"],
    "brand": "CONSUL",
    "stilRama": "ovala",
    "pentru": "dama",
    "pret": "300",
    "material": "acetat",
    "culoare": "visiniu",
    "cod": "86060C4",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0050",
    "clasa": "rame",
    "url": "/ochelari/DSC_0050.jpg",
    "carousel": ["/ochelari/DSC_0050.jpg", "/ochelari/DSC_0051.jpg"],
    "brand": "CORRADO",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "330",
    "material": "acetat",
    "culoare": "negru",
    "cod": "TR92011C1",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "18",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0052",
    "clasa": "rame",
    "url": "/ochelari/DSC_0052.jpg",
    "carousel": ["/ochelari/DSC_0052.jpg", "/ochelari/DSC_0053.jpg"],
    "brand": "FURLA",
    "stilRama": "rectangular",
    "pentru": "unisex",
    "pret": "480",
    "material": "acetat",
    "culoare": "verde/alb",
    "cod": "PELION VU4858",
    "tipRama": "rama completa",
    "latimeLentile": "58",
    "punteNazala": "14",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0054",
    "clasa": "rame",
    "url": "/ochelari/DSC_0054.jpg",
    "carousel": ["/ochelari/DSC_0054.jpg", "/ochelari/DSC_0055.jpg"],
    "brand": "SWAROVSKI",
    "stilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "570",
    "material": "acetat",
    "culoare": "maro",
    "cod": "FRIDA SW 5136",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "13",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0056",
    "clasa": "rame",
    "url": "/ochelari/DSC_0056.jpg",
    "carousel": ["/ochelari/DSC_0056.jpg", "/ochelari/DSC_0057.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "350",
    "material": "metal",
    "culoare": "visiniu/auriu",
    "cod": "MG3580C3",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0058",
    "clasa": "rame",
    "url": "/ochelari/DSC_0058.jpg",
    "carousel": ["/ochelari/DSC_0058.jpg", "/ochelari/DSC_0059.jpg"],
    "brand": "AVANGLION",
    "stilRama": "rotund",
    "pentru": "dama",
    "pret": "420",
    "material": "acetat",
    "culoare": "visiniu/roz",
    "cod": "AV14796C",
    "tipRama": "rama completa",
    "latimeLentile": "49",
    "punteNazala": "20",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0060",
    "clasa": "rame",
    "url": "/ochelari/DSC_0060.jpg",
    "carousel": ["/ochelari/DSC_0060.jpg", "/ochelari/DSC_0061.jpg"],
    "brand": "AVANGLION",
    "stilRama": "dreptunghiular",
    "pentru": "barbati",
    "pret": "420",
    "material": "acetat",
    "culoare": "negru/rosu",
    "cod": "AV10840A",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "16",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0062",
    "clasa": "rame",
    "url": "/ochelari/DSC_0062.jpg",
    "carousel": ["/ochelari/DSC_0062.jpg", "/ochelari/DSC_0064.jpg"],
    "brand": "POLICE",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "570",
    "material": "acetat",
    "culoare": "negru",
    "cod": "STAGEDIVE VPLA02",
    "tipRama": "rama completa",
    "latimeLentile": "48",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0065",
    "clasa": "rame",
    "url": "/ochelari/DSC_0065.jpg",
    "carousel": ["/ochelari/DSC_0065.jpg", "/ochelari/DSC_0066.jpg"],
    "brand": "GUESS",
    "stilRama": "dreptunghiular",
    "pentru": "unisex",
    "pret": "570",
    "material": "acetat",
    "culoare": "negru",
    "cod": "GU1995 001",
    "tipRama": "Rama completa",
    "latimeLentile": "54",
    "punteNazala": "15",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0067",
    "clasa": "rame",
    "url": "/ochelari/DSC_0067.jpg",
    "carousel": ["/ochelari/DSC_0067.jpg", "/ochelari/DSC_0068.jpg"],
    "brand": "GUESS",
    "stilRama": "paracetamol",
    "pentru": "barbati",
    "pret": "570",
    "material": "ultem",
    "culoare": "negru",
    "cod": "GU1982 002",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0069",
    "clasa": "rame",
    "url": "/ochelari/DSC_0069.jpg",
    "carousel": ["/ochelari/DSC_0069.jpg", "/ochelari/DSC_0070.jpg"],
    "brand": "VINTAGE",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "120",
    "material": "plastic",
    "culoare": "rosu",
    "cod": "77042",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "20",
    "lungimeBrat": "132",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0072",
    "clasa": "rame",
    "url": "/ochelari/DSC_0072.jpg",
    "carousel": ["/ochelari/DSC_0072.jpg", "/ochelari/DSC_0073.jpg"],
    "brand": "NIXUS",
    "stilRama": "dreptunghiular",
    "pentru": "barbati",
    "pret": "120",
    "material": "plastic",
    "culoare": "negru",
    "cod": "V626 C1",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0074",
    "clasa": "rame",
    "url": "/ochelari/DSC_0074.jpg",
    "carousel": ["/ochelari/DSC_0074.jpg", "/ochelari/DSC_0075.jpg"],
    "brand": "VINTAGE",
    "stilRama": "patrat",
    "pentru": "unisex",
    "pret": "120",
    "material": "plastic/metal",
    "culoare": "negru/auriu",
    "cod": "VTG1",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "20",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0076",
    "clasa": "rame",
    "url": "/ochelari/DSC_0076.jpg",
    "carousel": ["/ochelari/DSC_0076.jpg", "/ochelari/DSC_0077.jpg"],
    "brand": "SPRING",
    "stilRama": "oval",
    "pentru": "dama",
    "pret": "120",
    "material": "acetat",
    "culoare": "mov/negru",
    "cod": "V608",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "15",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0078",
    "clasa": "rame",
    "url": "/ochelari/DSC_0078.jpg",
    "carousel": ["/ochelari/DSC_0078.jpg", "/ochelari/DSC_0079.jpg"],
    "brand": "MODEL",
    "stilRama": "BEST MAN",
    "pentru": "dama",
    "pret": "150",
    "material": "plastic",
    "culoare": "negru",
    "cod": "5784",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0080",
    "clasa": "rame",
    "url": "/ochelari/DSC_0080.jpg",
    "carousel": ["/ochelari/DSC_0080.jpg", "/ochelari/DSC_0081.jpg"],
    "brand": "CHICLAMOUR",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "150",
    "material": "plastic",
    "culoare": "lila",
    "cod": "V772",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0082",
    "clasa": "rame",
    "url": "/ochelari/DSC_0082.jpg",
    "carousel": ["/ochelari/DSC_0082.jpg", "/ochelari/DSC_0083.jpg"],
    "brand": "CHARM",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "120",
    "material": "plastic",
    "culoare": "mov",
    "cod": "V658 C1",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0084",
    "clasa": "rame",
    "url": "/ochelari/DSC_0084.jpg",
    "carousel": ["/ochelari/DSC_0084.jpg", "/ochelari/DSC_0085.jpg"],
    "brand": "KIND",
    "stilRama": "oval",
    "pentru": "barbati",
    "pret": "120",
    "material": "plastic",
    "culoare": "maro",
    "cod": "K6221",
    "tipRama": "rama contur",
    "latimeLentile": "54",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0086",
    "clasa": "rame",
    "url": "/ochelari/DSC_0086.jpg",
    "carousel": ["/ochelari/DSC_0086.jpg", "/ochelari/DSC_0087.jpg"],
    "brand": "VITO FABIUS",
    "stilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "150",
    "material": "acetat",
    "culoare": "mov",
    "cod": "9012 C1",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "15",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0088",
    "clasa": "rame",
    "url": "/ochelari/DSC_0088.jpg",
    "carousel": ["/ochelari/DSC_0088.jpg", "/ochelari/DSC_0089.jpg"],
    "brand": "CHARM",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "120",
    "material": "plastic",
    "culoare": "grena",
    "cod": "V727 C1",
    "tipRama": "rama completa",
    "latimeLentile": "48",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0090",
    "clasa": "rame",
    "url": "/ochelari/DSC_0090.jpg",
    "carousel": ["/ochelari/DSC_0090.jpg", "/ochelari/DSC_0091.jpg"],
    "brand": "VINTAGE",
    "stilRama": "rotunda",
    "pentru": "unisex",
    "pret": "120",
    "material": "plastic/metal",
    "culoare": "negru/auriu",
    "cod": "VTG2",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "18",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0092",
    "clasa": "rame",
    "url": "/ochelari/DSC_0092.jpg",
    "carousel": ["/ochelari/DSC_0092.jpg", "/ochelari/DSC_0093.jpg"],
    "brand": "SENSUELLE",
    "stilRama ": "oval",
    "pentru": "unisex",
    "pret": "120",
    "material": "plastic",
    "culoare": "albastru",
    "cod": "MODELV762 C3",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "19",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0094",
    "clasa": "rame",
    "url": "/ochelari/DSC_0094.jpg",
    "carousel": ["/ochelari/DSC_0094.jpg", "/ochelari/DSC_0095.jpg"],
    "brand": "VITO FABIUS",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "150",
    "material": "acetat",
    "culoare": "albastru",
    "cod": "9025c2",
    "tipRama": "rama completa",
    "latimeLentile": "55",
    "punteNazala": "14",
    "lungimeBrat": "141",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0096",
    "clasa": "rame",
    "url": "/ochelari/DSC_0096.jpg",
    "carousel": ["/ochelari/DSC_0096.jpg", "/ochelari/DSC_0097.jpg"],
    "brand": "NEXUS",
    "stilRama": "oval",
    "pentru": "unisex",
    "pret": "186",
    "material": "acetat",
    "culoare": "albastru",
    "cod": "V697 C1",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0098",
    "clasa": "rame",
    "url": "/ochelari/DSC_0098.jpg",
    "carousel": ["/ochelari/DSC_0098.jpg", "/ochelari/DSC_0099.jpg"],
    "brand": "CHARM",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "150",
    "material": "plastic",
    "culoare": "veerde",
    "cod": "KA484 A76",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0100",
    "clasa": "rame",
    "url": "/ochelari/DSC_0100.jpg",
    "carousel": ["/ochelari/DSC_0100.jpg", "/ochelari/DSC_0101.jpg"],
    "brand": "ODYSEY",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "150",
    "material": "plastic",
    "culoare": "mov",
    "cod": "V698 H45",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "18",
    "lungimeBrat": "1400",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0102",
    "clasa": "rame",
    "url": "/ochelari/DSC_0102.jpg",
    "carousel": ["/ochelari/DSC_0102.jpg", "/ochelari/DSC_0103.jpg"],
    "brand": "C.C.O.K",
    "stilRama": "dreptunghiular",
    "pentru": "dama",
    "pret": "186",
    "material": "plastic",
    "culoare": "roz/albastru",
    "cod": "6048 r639",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0104",
    "clasa": "rame",
    "url": "/ochelari/DSC_0104.jpg",
    "carousel": ["/ochelari/DSC_0104.jpg", "/ochelari/DSC_0105.jpg"],
    "brand": "VITO FABIUS",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "165",
    "material": "plastic",
    "culoare": "negru/rosu",
    "cod": "6016C1",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0106",
    "clasa": "rame",
    "url": "/ochelari/DSC_0106.jpg",
    "carousel": ["/ochelari/DSC_0106.jpg", "/ochelari/DSC_0107.jpg"],
    "brand": "VITO FABIUS",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "177",
    "material": "acetat",
    "culoare": "roz/negru",
    "cod": "9025 C3",
    "tipRama": "rama completa ",
    "latimeLentile": "55",
    "punteNazala": "14",
    "lungimeBrat": "141",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0108",
    "clasa": "rame",
    "url": "/ochelari/DSC_0108.jpg",
    "carousel": ["/ochelari/DSC_0108.jpg", "/ochelari/DSC_0109.jpg"],
    "brand": "JACOPO",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "177",
    "material": "plastic",
    "culoare": "negru/grena",
    "cod": "61742 C5",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0110",
    "clasa": "rame",
    "url": "/ochelari/DSC_0110.jpg",
    "carousel": ["/ochelari/DSC_0110.jpg", "/ochelari/DSC_0111.jpg"],
    "brand": "VIZZINI",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "90",
    "material": "plastic",
    "culoare": "mov cu insertii",
    "cod": "V8094 C134",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0112",
    "clasa": "rame",
    "url": "/ochelari/DSC_0112.jpg",
    "carousel": ["/ochelari/DSC_0112.jpg", "/ochelari/DSC_0113.jpg"],
    "brand": "NICKOO",
    "stilRama": "rotund",
    "pentru": "uniseex",
    "pret": "80",
    "material": "metal",
    "culoare": "negru",
    "cod": "NKO 1",
    "tipRama": "rama intreaga",
    "latimeLentile": "50",
    "punteNazala": "20",
    "lungimeBrat": "133",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0114",
    "clasa": "rame",
    "url": "/ochelari/DSC_0114.jpg",
    "carousel": ["/ochelari/DSC_0114.jpg", "/ochelari/DSC_0115.jpg"],
    "brand": "ENZO",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "170",
    "material": "plastic",
    "culoare": "rosu",
    "cod": "ZH07C4",
    "tipRama": "rama intreaga",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0116",
    "clasa": "rame",
    "url": "/ochelari/DSC_0116.jpg",
    "carousel": ["/ochelari/DSC_0116.jpg", "/ochelari/DSC_0117.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "210",
    "material": "acetat",
    "culoare": "rosu",
    "cod": "GT7348",
    "tipRama": "rama intreaga",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0118",
    "clasa": "rame",
    "url": "/ochelari/DSC_0118.jpg",
    "carousel": ["/ochelari/DSC_0118.jpg", "/ochelari/DSC_0119.jpg"],
    "brand": "NICKOO",
    "stilRama": "animal print",
    "pentru": "dama",
    "pret": "210",
    "material": "acetat/metal",
    "culoare": "maro/negru",
    "cod": "8812 c2",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "19",
    "lungimeBrat": "81",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0120",
    "clasa": "rame",
    "url": "/ochelari/DSC_0120.jpg",
    "carousel": ["/ochelari/DSC_0120.jpg", "/ochelari/DSC_0121.jpg"],
    "brand": "NICKOO",
    "bstilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "320",
    "material": "acetat",
    "culoare": "crem/negru",
    "cod": "1222 C3",
    "tipRama": "rama completa",
    "latimeLentile": "54",
    "punteNazala": "14",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0122",
    "clasa": "rame",
    "url": "/ochelari/DSC_0122.jpg",
    "carousel": ["/ochelari/DSC_0122.jpg", "/ochelari/DSC_0123.jpg"],
    "brand": "POTYGO",
    "stilRama": "oval",
    "pentru": "dama",
    "pret": "230",
    "material": "acetat",
    "culoare": "crem/negru",
    "cod": "P 8017",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "17",
    "lungimeBrat": "142",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0124",
    "clasa": "rame",
    "url": "/ochelari/DSC_0124.jpg",
    "carousel": ["/ochelari/DSC_0124.jpg", "/ochelari/DSC_0125.jpg"],
    "brand": "PSSE",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "80",
    "material": "plastic",
    "culoare": "negru",
    "cod": "2360",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "17",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0126",
    "clasa": "rame",
    "url": "/ochelari/DSC_0126.jpg",
    "carousel": ["/ochelari/DSC_0126.jpg", "/ochelari/DSC_0127.jpg"],
    "brand": "CHARM",
    "stilRama": "patrat",
    "pentru": "unisex",
    "pret": "150",
    "material": "acetat",
    "culoare": "grena/verde",
    "cod": "V781 C5",
    "tipRama": " rama completa",
    "latimeLentile": "52",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0128",
    "clasa": "rame",
    "url": "/ochelari/DSC_0128.jpg",
    "carousel": ["/ochelari/DSC_0128.jpg", "/ochelari/DSC_0129.jpg"],
    "brand": "GROSSO",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "273",
    "material": "acetat",
    "culoare": "mov",
    "cod": "G 6006",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "15",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0130",
    "clasa": "rame",
    "url": "/ochelari/DSC_0130.jpg",
    "carousel": ["/ochelari/DSC_0130.jpg", "/ochelari/DSC_0131.jpg"],
    "brand": "MODERN LADY",
    "stilRama": "dreptunghiular",
    "pentru": "dama",
    "pret": "177",
    "material": "plastic/ metal",
    "culoare": "negru/auriu",
    "cod": "M626 C2Y",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0132",
    "clasa": "rame",
    "url": "/ochelari/DSC_0132.jpg",
    "carousel": ["/ochelari/DSC_0132.jpg", "/ochelari/DSC_0133.jpg"],
    "brand": "NICKOO",
    "stilRama": "rotund",
    "pentru": "dama",
    "pret": "170",
    "material": "plastic",
    "culoare": "portocaliu/maro",
    "cod": "G052 C7",
    "tipRama": "rama completa",
    "latimeLentile": "48",
    "punteNazala": "20",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0134",
    "clasa": "rame",
    "url": "/ochelari/DSC_0134.jpg",
    "carousel": ["/ochelari/DSC_0134.jpg", "/ochelari/DSC_0135.jpg"],
    "brand": "CONSUL",
    "stilRama": "rectangular",
    "pentru": " unisex",
    "pret": "183",
    "material": "acetat",
    "culoare": "maro",
    "cod": "86101c4",
    "tipRama": "rama completa",
    "latimeLentile": "49",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0136",
    "clasa": "rame",
    "url": "/ochelari/DSC_0136.jpg",
    "carousel": ["/ochelari/DSC_0136.jpg", "/ochelari/DSC_0137.jpg"],
    "brand": "CONSUL",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "320",
    "material": "acetat",
    "culoare": "turqouise/crem",
    "cod": "86097",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "17",
    "lungimeBrat": "135",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0138",
    "clasa": "rame",
    "url": "/ochelari/DSC_0138.jpg",
    "carousel": ["/ochelari/DSC_0138.jpg", "/ochelari/DSC_0139.jpg"],
    "brand": "CORRADO",
    "stilRama": "dreptunghiular/army",
    "pentru": "unisex",
    "pret": "420",
    "material": "ultem",
    "culoare": "gri",
    "cod": "88212",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0140",
    "clasa": "rame",
    "url": "/ochelari/DSC_0140.jpg",
    "carousel": ["/ochelari/DSC_0140.jpg", "/ochelari/DSC_0141.jpg"],
    "brand": "MYSTERY",
    "stilRama": "rectangular",
    "pentru": "barbati",
    "pret": "260",
    "material": "acetat",
    "culoare": "negru",
    "cod": "405 c1",
    "tipRama": "rama completa",
    "latimeLentile": "55",
    "punteNazala": "19",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0142",
    "clasa": "rame",
    "url": "/ochelari/DSC_0142.jpg",
    "carousel": ["/ochelari/DSC_0142.jpg", "/ochelari/DSC_0143.jpg"],
    "brand": "PEIEP",
    "stilRama": "dreptunghiular",
    "pentru": "barbati",
    "pret": "375",
    "material": "ultem",
    "culoare": "negru",
    "cod": "MODEL",
    "tipRama": "rama completa",
    "latimeLentile": "56",
    "punteNazala": "16",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0144",
    "clasa": "rame",
    "url": "/ochelari/DSC_0144.jpg",
    "carousel": ["/ochelari/DSC_0144.jpg", "/ochelari/DSC_0145.jpg"],
    "brand": "SENSUELLE",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "120lei",
    "material": "plastic",
    "culoare": "maro",
    "cod": "V774 C2",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0146",
    "clasa": "rame",
    "url": "/ochelari/DSC_0146.jpg",
    "carousel": ["/ochelari/DSC_0146.jpg", "/ochelari/DSC_0147.jpg"],
    "brand": "CADRU OPTIC",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "310",
    "material": "acetat",
    "culoare": "negru/roz",
    "cod": " R7010 C5",
    "tipRama": "rama completa",
    "latimeLentile": "56",
    "punteNazala": "16",
    "lungimeBrat": "139",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0148",
    "clasa": "rame",
    "url": "/ochelari/DSC_0148.jpg",
    "carousel": ["/ochelari/DSC_0148.jpg", "/ochelari/DSC_0149.jpg"],
    "brand": "RICH PERSON",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "282",
    "material": "ultem",
    "culoare": "grena",
    "cod": "T20915C5B11",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  // {
  //   "id": "DSC_0150",
  //   "clasa": "rame",
  //   "url": "/ochelari/DSC_0150.jpg",
  //   "carousel": ["/ochelari/DSC_0150.jpg", "/ochelari/DSC_0151.jpg"],
  //   "nume": "VANDUT",
  //   "brand": "MODEL",
  //   "pentru": "MODEL",
  //   "pret": "MODEL",
  //   "material": "MODEL",
  //   "culoare": "MODEL",
  //   "cod": "MODEL",
  //   "inaltimeLentile": "MODEL",
  //   "latimeLentile": "MODEL",
  //   "punteNazala": "MODEL",
  //   "lungimeBrat": "MODEL",
  //   "width": "1920",
  //   "height": "1080",
  // },
  {
    "id": "DSC_0152",
    "clasa": "rame",
    "url": "/ochelari/DSC_0152.jpg",
    "carousel": ["/ochelari/DSC_0152.jpg", "/ochelari/DSC_0153.jpg"],
    "brand": "FENDI",
    "stilRama": "patrat",
    "pentru": "dama",
    "pret": "350",
    "material": "acetat",
    "culoare": "negru",
    "cod": "8201",
    "tipRama": "rama completa",
    "latimeLentila": "60",
    "punteNazala": "12",
    "lungimeBrat": "143",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0154",
    "clasa": "rame",
    "url": "/ochelari/DSC_0154.jpg",
    "carousel": ["/ochelari/DSC_0154.jpg", "/ochelari/DSC_0155.jpg"],
    "brand": "LOUIS VUITTON",
    "stilRama": "patrat",
    "pentru": "barbati",
    "pret": "350",
    "material": "acetat",
    "culoare": "negru",
    "cod": "8612",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0156",
    "clasa": "rame",
    "url": "/ochelari/DSC_0156.jpg",
    "carousel": ["/ochelari/DSC_0156.jpg", "/ochelari/DSC_0157.jpg"],
    "brand": "CHARM",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "123",
    "material": "plastic",
    "culoare": "mov/grena",
    "cod": "V758 C4",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0158",
    "clasa": "rame",
    "url": "/ochelari/DSC_0158.jpg",
    "carousel": ["/ochelari/DSC_0158.jpg", "/ochelari/DSC_0159.jpg"],
    "brand": "C.C.D.K",
    "stilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "170",
    "material": "plastic",
    "culoare": "negru/verde",
    "cod": "6057 R657",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  // {
  //   "id": "DSC_0160",
  //   "clasa": "rame",
  //   "url": "/ochelari/DSC_0160.jpg",
  //   "carousel": ["/ochelari/DSC_0160.jpg", "/ochelari/DSC_0161.jpg"],
  //   "nume": "VANDUT",
  //   "brand": "MODEL",
  //   "pentru": "MODEL",
  //   "pret": "MODEL",
  //   "material": "MODEL",
  //   "culoare": "MODEL",
  //   "cod": "MODEL",
  //   "inaltimeLentile": "MODEL",
  //   "latimeLentile": "MODEL",
  //   "punteNazala": "MODEL",
  //   "lungimeBrat": "MODEL",
  //   "width": "1920",
  //   "height": "1080",
  // },
  {
    "id": "DSC_0162",
    "clasa": "rame",
    "url": "/ochelari/DSC_0162.jpg",
    "carousel": ["/ochelari/DSC_0162.jpg", "/ochelari/DSC_0163.jpg"],
    "brand": "NICKOO",
    "stilRama": "rectangular",
    "pentru": "barbati",
    "pret": "300",
    "material": "acetat",
    "culoare": "negru",
    "cod": "8182 c7",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "17",
    "lungimeBrat": "139",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0164",
    "clasa": "rame",
    "url": "/ochelari/DSC_0164.jpg",
    "carousel": ["/ochelari/DSC_0164.jpg", "/ochelari/DSC_0165.jpg"],
    "brand": "AUTOMAN",
    "stilRama": "rectangulara",
    "pentru": "dama",
    "pret": "210",
    "material": "metal",
    "culoare": "negru/roz",
    "cod": "A019 C2",
    "tipRama": "rama completa",
    "latimeLentile": "49",
    "punteNazala": "14",
    "lungimeBrat": "130",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0166",
    "clasa": "rame",
    "url": "/ochelari/DSC_0166.jpg",
    "carousel": ["/ochelari/DSC_0166.jpg", "/ochelari/DSC_0167.jpg"],
    "brand": "NICKOO",
    "stilRama": "rotunda",
    "pentru": "unisex",
    "pret": "170",
    "material": "plastic",
    "culoare": "negru",
    "cod": "8220",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "20",
    "lungimeBrat": "153",
    "width": "1920",
    "height": "1080",
  },
  // {
  //   "id": "DSC_0168",
  //   "clasa": "rame",
  //   "url": "/ochelari/DSC_0168.jpg",
  //   "carousel": ["/ochelari/DSC_0168.jpg", "/ochelari/DSC_0169.jpg"],
  //   "nume": "VANDUT",
  //   "brand": "MODEL",
  //   "pentru": "MODEL",
  //   "pret": "MODEL",
  //   "material": "MODEL",
  //   "culoare": "MODEL",
  //   "cod": "MODEL",
  //   "inaltimeLentile": "MODEL",
  //   "latimeLentile": "MODEL",
  //   "punteNazala": "MODEL",
  //   "lungimeBrat": "MODEL",
  //   "width": "1920",
  //   "height": "1080",
  // },
  {
    "id": "DSC_0170",
    "clasa": "rame",
    "url": "/ochelari/DSC_0170.jpg",
    "carousel": ["/ochelari/DSC_0170.jpg", "/ochelari/DSC_0171.jpg"],
    "brand": "CHARM",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "120",
    "material": "plastic",
    "culoare": "mov",
    "cod": "V658 C1",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0172",
    "clasa": "rame",
    "url": "/ochelari/DSC_0172.jpg",
    "carousel": ["/ochelari/DSC_0172.jpg", "/ochelari/DSC_0173.jpg"],
    "brand": "CADRU OPTIC",
    "stilRama": "dreptunghiular",
    "pentru": "dama",
    "pret": "330",
    "material": "acetat",
    "culoare": "negru",
    "cod": "R7008 C 15",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0174",
    "clasa": "rame",
    "url": "/ochelari/DSC_0174.jpg",
    "carousel": ["/ochelari/DSC_0174.jpg", "/ochelari/DSC_0175.jpg"],
    "brand": "GIO",
    "stilRama": "ochi de pisica",
    "pentru": "dama",
    "pret": "147",
    "material": "plastic",
    "culoare": "roz",
    "cod": "G203 C1",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0176",
    "clasa": "rame",
    "url": "/ochelari/DSC_0176.jpg",
    "carousel": ["/ochelari/DSC_0176.jpg", "/ochelari/DSC_0177.jpg"],
    "brand": "NISUS",
    "stilRama": "oval",
    "pentru": "unisex",
    "pret": "120",
    "material": "acetat",
    "culoare": "maro",
    "cod": "V697 C5",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0178",
    "clasa": "rame",
    "url": "/ochelari/DSC_0178.jpg",
    "carousel": ["/ochelari/DSC_0178.jpg", "/ochelari/DSC_0179.jpg"],
    "brand": "PEIEP",
    "stilRama": "dreptunghiulara",
    "pentru": "unisex",
    "pret": "370",
    "material": "ultem memory",
    "culoare": "negru",
    "cod": "ULTEM 081",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "15",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0180",
    "clasa": "rame",
    "url": "/ochelari/DSC_0180.jpg",
    "carousel": ["/ochelari/DSC_0180.jpg", "/ochelari/DSC_0181.jpg"],
    "brand": "MYSTERY",
    "stilRama": "dreptunghiular",
    "pentru": "barbati",
    "pret": "210",
    "material": "acetat",
    "culoare": "negru",
    "cod": "387 c7",
    "tipRama": "rama completa",
    "latimeLentile": "56",
	  "punteNazala": "18",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0182",
    "clasa": "rame",
    "url": "/ochelari/DSC_0182.jpg",
    "carousel": ["/ochelari/DSC_0182.jpg", "/ochelari/DSC_0184.jpg"],
    "brand": "PEIEP",
    "stilRama": "ultem memory",
    "pentru": "unisex",
    "pret": "390",
    "material": "ultem",
    "culoare": "negru",
    "cod": "ULTEM 1627",
    "tipRama": "rama completa",
    "latimeLentile": "50",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0185",
    "clasa": "rame",
    "url": "/ochelari/DSC_0185.jpg",
    "carousel": ["/ochelari/DSC_0185.jpg", "/ochelari/DSC_0186.jpg"],
    "brand": "SPRING",
    "stilRama": "rectangular",
    "pentru": "barbati",
    "pret": "150",
    "material": "plastic",
    "culoare": "negru",
    "cod": "V647 C1",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0187",
    "clasa": "rame",
    "url": "/ochelari/DSC_0187.jpg",
    "carousel": ["/ochelari/DSC_0187.jpg", "/ochelari/DSC_0188.jpg"],
    "brand": "PEIEP",
    "stilRama": "rectangular",
    "pentru": "barbati",
    "pret": "375",
    "material": "ultem memory",
    "culoare": "negru",
    "cod": " ultem 050",
    "tipRama": "rama completa",
    "latimeLentile": "56",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0189",
    "clasa": "rame",
    "url": "/ochelari/DSC_0189.jpg",
    "carousel": ["/ochelari/DSC_0189.jpg", "/ochelari/DSC_0190.jpg"],
    "brand": "LEDIX",
    "stilRama": "rectangular",
    "pentru": "unisex",
    "pret": "240",
    "material": "acetat",
    "culoare": "negru",
    "cod": "LO22 A41",
    "tipRama": "rama completa",
    "latimeLentile": "49",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0191",
    "clasa": "rame",
    "url": "/ochelari/DSC_0191.jpg",
    "carousel": ["/ochelari/DSC_0191.jpg", "/ochelari/DSC_0192.jpg"],
    "brand": "CHIARA",
    "stilRama": "dreptunghiular",
    "pentru": "unisex",
    "pret": "150",
    "material": "plastic",
    "culoare": "negru",
    "cod": "T859 C1",
    "tipRama": "rama completa",
    "latimeLentile": "55",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0193",
    "clasa": "rame",
    "url": "/ochelari/DSC_0193.jpg",
    "carousel": ["/ochelari/DSC_0193.jpg", "/ochelari/DSC_0194.jpg"],
    "brand": "CORRADO",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "250",
    "material": "acetat",
    "culoare": "maro",
    "cod": "88027 c2",
    "tipRama": "rectangulara",
    "latimeLentile": "52",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0195",
    "clasa": "rame",
    "url": "/ochelari/DSC_0195.jpg",
    "carousel": ["/ochelari/DSC_0195.jpg", "/ochelari/DSC_0196.jpg"],
    "brand": "MODEL",
    "stilRama": "rectangular",
    "pentru": "unisex",
    "pret": "170",
    "material": "plastic",
    "culoare": "negru",
    "cod": "v8672",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "17",
    "lungimeBrat": "145",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0197",
    "clasa": "rame",
    "url": "/ochelari/DSC_0197.jpg",
    "carousel": ["/ochelari/DSC_0197.jpg", "/ochelari/DSC_0198.jpg"],
    "brand": "VIZZINI",
    "stilRama": "ochi pisica",
    "pentru": "dama",
    "pret": "150",
    "material": "plastic",
    "culoare": "mov",
    "cod": "V8685 C159",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "16",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0199",
    "clasa": "rame",
    "url": "/ochelari/DSC_0199.jpg",
    "carousel": ["/ochelari/DSC_0199.jpg", "/ochelari/DSC_0200.jpg"],
    "brand": "CARDY DONY",
    "stilRama": "rotund",
    "pentru": "dama",
    "pret": "260",
    "material": "metal/plastic",
    "culoare": "ruginiu",
    "cod": "CD004 C4",
    "tipRama": "rama completa",
    "latimeLentile": "48",
    "punteNazala": "21",
    "lungimeBrat": "138",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0201",
    "clasa": "rame",
    "url": "/ochelari/DSC_0201.jpg",
    "carousel": ["/ochelari/DSC_0201.jpg", "/ochelari/DSC_0202.jpg"],
    "brand": "CONSUL",
    "stilRama": "rectangular",
    "pentru": "dama",
    "pret": "312",
    "material": "acetat",
    "culoare": "rosu",
    "cod": "T856 C5",
    "tipRama": "rama completa",
    "latimeLentile": "51",
    "punteNazala": "17",
    "lungimeBrat": "142",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0203",
    "clasa": "rame",
    "url": "/ochelari/DSC_0203.jpg",
    "carousel": ["/ochelari/DSC_0203.jpg", "/ochelari/DSC_0204.jpg"],
    "brand": "C.C.D.K",
    "stilRama": "dreptunghiular",
    "pentru": "dama",
    "pret": "120",
    "material": "plastic",
    "culoare": "grena",
    "cod": "CK066 R80",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "17",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0205",
    "clasa": "rame",
    "url": "/ochelari/DSC_0205.jpg",
    "carousel": ["/ochelari/DSC_0205.jpg", "/ochelari/DSC_0206.jpg"],
    "brand": "POBI",
    "stilRama": "rotund",
    "pentru": "unisex",
    "pret": "174",
    "material": "plastic/metal",
    "culoare": "negru/auriu",
    "cod": "POBI WX3197",
    "tipRama": "rama completa",
    "latimeLentile": "53",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0207",
    "clasa": "rame",
    "url": "/ochelari/DSC_0207.jpg",
    "carousel": ["/ochelari/DSC_0207.jpg", "/ochelari/DSC_0208.jpg"],
    "brand": "VIZZINI",
    "stilRama": "rectangular",
    "pentru": "unisex",
    "pret": "180",
    "material": "plastic",
    "culoare": "negru/grena",
    "cod": "V8621 C14",
    "tipRama": "rama completa",
    "latimeLentile": "52",
    "punteNazala": "18",
    "lungimeBrat": "140",
    "width": "1920",
    "height": "1080",
  },
  {
    "id": "DSC_0209",
    "clasa": "rame",
    "url": "/ochelari/DSC_0209.jpg",
    "carousel": ["/ochelari/DSC_0209.jpg", "/ochelari/DSC_0210.jpg"],
    "brand": "PANORAMA KIDS",
    "stilRama": "rectangular",
    "pentru": "copii",
    "pret": "275",
    "material": "plastic/silicon",
    "culoare": "negru/verde",
    "cod": "LDS1054",
    "tipRama": "rama completa",
    "latimeLentile": "45",
    "punteNazala": "17",
    "lungimeBrat": "125",
    "width": "1920",
    "height": "1080",
  },
  { "id": "21", "clasa": "accesorii", "culoare": "verde", "url": "/accesorii/laveta1.jpg", "carousel": ["/accesorii/laveta1.jpg"], "cod": "49374", "material": "bumbac", "name": "Laveta1", "pret": 42, "width": "2000", "height": "1125" },
  { "id": "22", "clasa": "accesorii", "culoare": "rosu", "url": "/accesorii/laveta2.jpg", "carousel": ["/accesorii/laveta2.jpg"], "cod": "75629", "material": "lana", "name": "Laveta2", "pret": 79, "width": "800", "height": "450" },
  { "id": "23", "clasa": "accesorii", "culoare": "albastru", "url": "/accesorii/laveta3.jpg", "carousel": ["/accesorii/laveta3.jpg"], "cod": "54976", "material": "bumbac", "name": "Laveta3", "pret": 48, "width": "800", "height": "450" },
  { "id": "24", "clasa": "accesorii", "culoare": "verde", "url": "/accesorii/laveta4.jpg", "carousel": ["/accesorii/laveta4.jpg"], "cod": "92809", "material": "bumbac", "name": "Laveta4", "pret": 91, "width": "1200", "height": "675" },
  { "id": "25", "clasa": "accesorii", "culoare": "portocaliu", "url": "/accesorii/laveta5.jpg", "carousel": ["/accesorii/laveta5.jpg"], "cod": "92981", "material": "lana", "name": "Laveta5", "pret": 17, "width": "800", "height": "450" },
  { "id": "26", "clasa": "accesorii", "culoare": "verde", "url": "/accesorii/laveta6.jpg", "carousel": ["/accesorii/laveta6.jpg"], "cod": "58565", "material": "bumbac", "name": "Laveta6", "pret": 48, "width": "1200", "height": "675" },
  { "id": "27", "clasa": "accesorii", "culoare": "verde", "url": "/accesorii/laveta7.jpg", "carousel": ["/accesorii/laveta7.jpg"], "cod": "81986", "material": "lana", "name": "Laveta7", "pret": 94, "width": "1000", "height": "562" },
  { "id": "28", "clasa": "accesorii", "culoare": "verde", "url": "/accesorii/laveta8.jpg", "carousel": ["/accesorii/laveta8.jpg"], "cod": "52561", "material": "bumbac", "name": "Laveta8", "pret": 45, "width": "485", "height": "273" },
  { "id": "29", "clasa": "lentile", "url": "/lentile/lens1.jpg", "carousel": ["/lentile/lens1.jpg"], "cod": "52562", "material": "sticla", "name": "Lentila convexa", "pret": 142, "width": "1000", "height": "562" },
  { "id": "30", "clasa": "lentile", "url": "/lentile/lens2.jpg", "carousel": ["/lentile/lens2.jpg"], "cod": "52563", "material": "organica", "name": "Lentila concava", "pret": 250, "width": "900", "height": "506" },
]

const LENTILE = [
  { id: '', name: '', tip: '', dioptrie: '' },
]


export const getIndexData = () => {
    return new Promise((resolve, reject) => {
        // first arg is a function, second arg is the time
        setTimeout(() => {
            resolve(INDEX_DATA)
            // reject('Cannot fetch data.')
        }, 50)
    })
}

export const getProduse = () => {
    return new Promise((resolve, reject) => {
        // first arg is a function, second arg is the time
        setTimeout(() => {
            resolve(PRODUSE)
            // reject('Cannot fetch data.')
        }, 50)
    })
}

